# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test.xci
# IP: The module: 'fifo_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test/fifo_test_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_test'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test/fifo_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: D:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test.xci
# IP: The module: 'fifo_test' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test/fifo_test_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test/fifo_test.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: d:/USA/video/Verilog_Vivado_FIFO/prj_FIFO/prj_FIFO.srcs/sources_1/ip/fifo_test/fifo_test_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_test'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
